import type {TableData} from "@/components/ServiceJournal/serviceJournal.types";

export const data: TableData[] = [
    {
        key: "1",
        name: "gavrilov",
        theme: "Электронная почта",
        number: "95708",
        creationDate: "20.05.2024 15:22",
        changeDate: "20.05.2024 17:22",
        term: "21.05.2024 15:22",
        status: "В работе",
        waiting: "Нет",
        description: "Прошу сделать переадресацию на время отпуска",
        solution: "",
        service: "Интернет",
        serviceComposition: "Почта"
    },
    {
        key: "2",
        name: "gavrilov",
        theme: "Установка платформы",
        number: "95802",
        creationDate: "22.05.2024 11:03",
        changeDate: "22.05.2024 11:03",
        term: "23.05.2024 11:03",
        status: "Зарегистрировано",
        waiting: "Нет",
        description: "Прошу установить платформу 8.3.24",
        solution: "",
        service: "Поддержка рабочих мест",
        serviceComposition: "Настройка ПО"
    },
    {
        key: "3",
        name: "gavrilov",
        theme: "Подключение к сети",
        number: "95803",
        creationDate: "24.05.2024 9:41",
        changeDate: "24.05.2024 11:41",
        term: "25.05.2024 9:41",
        status: "На согласовании",
        waiting: "Нет",
        description: "Нужен доступ к serversoft",
        solution: "",
        service: "Интернет",
        serviceComposition: "Доступ"
    },
    {
        key: "4",
        name: "gavrilov",
        theme: "Установка ПО на ПК",
        number: "95804",
        creationDate: "24.05.2024 12:30",
        changeDate: "24.05.2024 12:30",
        term: "25.05.2024 12:30",
        status: "Выполнено. Требует подтверждения",
        waiting: "Да",
        description: "Для нового сотрудника нужна IDE",
        solution: "Софт установлен",
        service: "Поддержка рабочих мест",
        serviceComposition: "Настройка ПО"
    },
    {
        key: "5",
        name: "gavrilov",
        theme: "Проблема с сетью",
        number: "95901",
        creationDate: "25.05.2024 10:07",
        changeDate: "26.05.2024 9:00",
        term: "26.05.2024 10:07",
        status: "Зарегистрировано",
        waiting: "Нет",
        description: "Не заходит на внешние сайты при включенном впн",
        solution: "",
        service: "Интернет",
        serviceComposition: "Доступ"
    },
    {
        key: "6",
        name: "gavrilov",
        theme: "Установка проектора",
        number: "95902",
        creationDate: "27.05.2024 14:11",
        changeDate: "27.05.2024 14:11",
        term: "28.05.2024 14:11",
        status: "Закрыто",
        waiting: "Нет",
        description: "В ауд. 312. Проектор установлен",
        solution: "",
        service: "Поддержка рабочих мест",
        serviceComposition: "Настройка оборудования"
    },
    {
        key: "7",
        name: "gavrilov",
        theme: "Активация Office",
        number: "95903",
        creationDate: "29.05.2024 13:15",
        changeDate: "29.05.2024 13:15",
        term: "30.05.2024 13:15",
        status: "На согласовании",
        waiting: "Да",
        description: "Требуется офис на выездном ноутбуке",
        solution: "Активирован 2016",
        service: "Поддержка рабочих мест",
        serviceComposition: "Настройка ПО"
    },
]